sudo: false

language: node_js

node_js:
  - "6"
  - "4"
  - "iojs"

cache:
  directories:
    - node_modules

script:
  - npm run test

deploy:
  provider: heroku
  api_key:
    secure: ffd2b156-71d1-4dd5-9fde-c026bc5f0c4c
